# config
description: "A snarky theme by psharma04"

# comment system
valine: ## https://valine.js.org
  enable: false ## If you want to use Valine comment system, please set the value to true.
  appid: ## Your LeanCloud application App ID, e.g. pRBBL2JR4N7kLEGojrF0MsSs-gzGzoHsz
  appkey: ## Your LeanCloud application App Key, e.g. tjczHpDfhjYDSYddzymYK1JJ
  notify: false ## Mail notifier, see https://github.com/xCss/Valine/wiki/Valine-评论系统中的邮件提醒设置
  verify: false ## Validation code.
  placeholder: "ヾﾉ≧∀≦)o Come on, say something..." ## Comment box placeholders.
  avatar: 'identicon' ## Gravatar type, see https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
  pageSize: 10 ## Number of comments per page.
  guest_info: nick,mail,link ## Attributes of reviewers.


busuanzi: true  ## If you want show counter of views, please set the value to true
local_search: true
customize_css: true  ## if enable customize_css, it will load file source/css/customize.scss
fancybox: true  ## for image view
copyright: true ## for CC BY-NC 4.0 license

menu:
  - page: Archives
    directory: archives/
  - page: Categories
    directory: categories/
  - page: Tags
    directory: tags/
  - page: About
    directory: about/
  - page: rss
    directory: atom.xml

icons:
  date: fa fa-calendar
  category: fa fa-folder
  tag: fa fa-tag
  tags: fa fa-tags
  view: fa fa-eye
  visitor: fa fa-user

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  #- search
  #- category
  #- tag
  #- recent_posts
  #- recent_comments
  #- links

links:
  - title: friend-1
    url: https://www.friend-1.com

# Static files
js: js
css: css
plugins: plugins

# Theme version
version: 0.0.1
